// <auto-generated />
using BlazorLeaflet.Samples.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorLeaflet.Samples.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20200723075906_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("BlazorLeaflet.Samples.Data.Hotels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("activity_area")
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("district")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("street")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Latitude = 40.112758999999997,
                            Longitude = 26.406562999999998,
                            No = 2,
                            activity_area = "Açık ve Kapalı Havuz,Spa,Restoran",
                            city = "Çanakkale",
                            district = "Merkez",
                            image = "https://imagessl.etstur.com/files/images/hotelImages/integration/TR/94131/l/s5cu25fseia0a4ruyzif.jpg",
                            name = "Kolin Hotel",
                            phone = "+902862180808",
                            street = "Atatürk Caddesi"
                        },
                        new
                        {
                            ID = 2,
                            Latitude = 40.153368,
                            Longitude = 26.407924999999999,
                            No = 2,
                            activity_area = "Restoran",
                            city = "Çanakkale",
                            district = "Merkez",
                            image = "https://imagessl.etstur.com/files/images/hotelImages/integration/TR/51416/l/lu0axr1mij2jnljgrqzt.jpg",
                            name = "Büyük Truva Hotel",
                            phone = "+902862171024",
                            street = "Mehmet Akif Ersoy Cd."
                        },
                        new
                        {
                            ID = 3,
                            Latitude = 40.149659999999997,
                            Longitude = 26.404779999999999,
                            No = 4,
                            activity_area = "",
                            city = "Çanakkale",
                            district = "Merkez",
                            image = "https://imagessl.etstur.com/files/images/hotelImages/integration/TR/91088/l/mfih5nuhidb7r7ifn4ow.jpg",
                            name = "Grand Ece Hotel",
                            phone = "+902862139345",
                            street = "Değirmenlik 1.Çıkmazı Sk."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
